-- MySQL Script generated by MySQL Workbench
-- Ter 13 Mar 2018 12:44:34 BRT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema gerenciaCearaCientifico
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema gerenciaCearaCientifico
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gerenciaCearaCientifico` DEFAULT CHARACTER SET utf8 ;
USE `gerenciaCearaCientifico` ;

-- -----------------------------------------------------
-- Table `gerenciaCearaCientifico`.`login_ava`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gerenciaCearaCientifico`.`login_ava` (
  `id` INT(4) NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(25) NOT NULL,
  `senha` VARCHAR(12) NOT NULL,
  `area` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gerenciaCearaCientifico`.`tbl_projet_dados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gerenciaCearaCientifico`.`tbl_projet_dados` (
  `id_tbl_projet_dados` INT(11) NOT NULL AUTO_INCREMENT,
  `nome_alu_tbl_projeto_dados` VARCHAR(45) NOT NULL,
  `turma_alu_tbl_projeto_dados` VARCHAR(45) NOT NULL,
  `num_alu_tbl_projeto_dados` VARCHAR(45) NOT NULL,
  `ano_alu_tbl_projeto_dados` INT(3) NOT NULL,
  `nome_tbl_projeto_dados` VARCHAR(45) NOT NULL,
  `orien_tbl_projeto_dados` VARCHAR(45) NOT NULL,
  `area_tbl_projeto_dados` VARCHAR(45) NOT NULL,
  `contxt_tbl_projeto_dados` VARCHAR(200) NOT NULL,
  `objt_tbl_projeto_dados` VARCHAR(200) NOT NULL,
  `metodo_tbl_projeto_dados` VARCHAR(200) NOT NULL,
  `relev_tbl_projeto_dados` VARCHAR(200) NOT NULL,
  `impact_tbl_projeto_dados` VARCHAR(200) NOT NULL,
  `condFin_tbl_projeto_dados` VARCHAR(200) NOT NULL,
  `nomeImg_tbl_projeto_dados` VARCHAR(450) NOT NULL,
  PRIMARY KEY (`id_tbl_projet_dados`))
ENGINE = InnoDB
AUTO_INCREMENT = 19
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
