-- MySQL Script generated by MySQL Workbench
-- Tue Aug 21 13:29:38 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema teste_petiscaria
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema teste_petiscaria
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `teste_petiscaria` DEFAULT CHARACTER SET utf8 ;
USE `teste_petiscaria` ;

-- -----------------------------------------------------
-- Table `teste_petiscaria`.`estoque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `teste_petiscaria`.`estoque` (
  `id_produto` INT NOT NULL AUTO_INCREMENT,
  `nome_produto` VARCHAR(45) NOT NULL,
  `qtd_produto` VARCHAR(45) NOT NULL,
  `preco_produto` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`id_produto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `teste_petiscaria`.`mesas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `teste_petiscaria`.`mesas` (
  `id_mesa` INT NOT NULL AUTO_INCREMENT,
  `num_mesa` INT NOT NULL,
  `status_mesa` TINYINT NOT NULL,
  PRIMARY KEY (`id_mesa`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
