-- MySQL Script generated by MySQL Workbench
-- Seg 26 Mar 2018 10:01:20 BRT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema img
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema img
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `img` DEFAULT CHARACTER SET latin1 ;
USE `img` ;

-- -----------------------------------------------------
-- Table `img`.`imagem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `img`.`imagem` (
  `id` INT(9) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
